openapi: 3.0.0
info:
  title: Book Management API
  description: API for managing books
  version: 1.0.0
servers:
  - url: http://localhost:3000
    

paths:
  /books:
    get:
      summary: Get all books
      responses:
        200:
          description: A list of books
          content:
            application/json:
              schema:
                type: array
                items:
                  
                  type: object
                  properties:
                    id:
                      type: integer
                    title:
                      type: string
                    completed:
                      type: boolean
    post:
      summary: Create a new book
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                completed:
                  type: boolean
      responses:
        201:
          description: Book created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  completed:
                    type: boolean

  /books/{id}:
    get:
      summary: Get a book by ID
      
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: The ID of the book
      responses:
        200:
          description: Book details
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  completed:
                    type: boolean
        404:
          description: Book not found

    put:
      summary: Update a book by ID
      
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: The ID of the book
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                completed:
                  type: boolean
      responses:
        200:
          description: Book updated successfully
        404:
          description: Book not found

    delete:
      summary: Delete a book by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: The ID of the book
      responses:
        204:
          description: Book deleted successfully



